myportsite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    # path('', views.Index.as_view(), name='home'),
    path('', views.index, name="todo"),
    path('del/', views.remove, name="del"),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productivity/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    # path('', views.Index.as_view(), name='home'),
    path('', views.index, name="todo"),
    path('del/', views.remove, name="del"),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productivity/models.py
from django.db import models
from django.utils import timezone

class Board(models.Model):
     name = models.CharField(max_length=30, blank=True, default="New Board", unique=True)
     description = models.TextField(blank=True)

     def __str__(self):
        return self.name

class TodoGroup(models.Model):
    name = models.CharField(max_length=30, blank=True, default="New Group")
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class TodoList(models.Model):
     name = models.CharField(max_length=30, blank=True, default="New To-Do")
     subtitle = models.CharField(max_length=30, blank=True, default="")
     date_submit = models.DateTimeField(default=timezone.now)
     board = models.ForeignKey(Board, on_delete=models.CASCADE)
     group = models.ForeignKey(TodoGroup, on_delete=models.CASCADE, blank=True, null=True)

     def __str__(self):
        return self.name

class TodoItem(models.Model):
    name = models.CharField(max_length=30, blank=True, default="")
    date_submit = models.DateTimeField(default=timezone.now)
    completed = models.BooleanField(default=False)
    recurring = models.BooleanField(default=False)
    recur_interval = models.DurationField(blank=True, null=True)
    recur_adjust = models.BooleanField(default=False)
    due_ool = models.BooleanField(default=False)
    date_due = models.DateTimeField(blank=True, null=True)
    urgent = models.BooleanField(default=False)
    today = models.BooleanField(default=False)
    overdue = models.BooleanField(default=False)
    list = models.ForeignKey(TodoList, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class TodoSubitem(models.Model):
    name = models.CharField(max_length=30, blank=True, default="")
    completed = models.BooleanField(default=False)
    urgent = models.BooleanField(default=False)
    today = models.BooleanField(default=False)
    item = models.ForeignKey(TodoItem, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

productivity/forms.py
from django import forms
from .models import TodoList

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields="__all__"

productivity/views.py
from django.views.generic import TemplateView
# copied from https://www.geeksforgeeks.org/python-todo-webapp-using-django/
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import TodoForm
from .models import TodoList, Board, TodoItem

class Index(TemplateView):
    template_name = 'home.html'

def index(request):
    todo_list = TodoList.objects.order_by("-date_submit")
    board_list = Board.objects.all()
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo')
    form = TodoForm()

    context = {
        "forms" : form,
        "todo_list" : todo_list,
        "board" : board_list,
        "title" : "TODO LIST",
    }
    return render(request, 'home.html', context)

### function to remove item, it recive todo item id from url ##
def remove(request, item_id):
    item = TodoList.objects.get(id=item_id)
    item.delete()
    messages.info(request, "item removed !!!")
    return redirect('todo')

productivity/templates/productivity/home.html
<!DOCTYPE html>

<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/override.css' %}">
    {% block styles %} {% endblock styles %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script src={% static 'js/productivity.js' %}></script>
    {% block scripts %}{% endblock scripts %}
    <title>{% block title %}Productivity Planner{% endblock title %}</title>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row header">
        <div class="col"> Welcome, Kayko! </div>
        <div class="col text-center"> DateTime </div>
        <div class="col text-right"> Weather </div>
      </div>
    </div>
    <nav class="nav-bar navbar-fixed-top">
      <div class="container-fluid" style="padding:0px">
        <ul class="nav nav-tabs" role="tablist">
          <li>
            <a class="btn btn-sample active" id="nav-dashboard-tab" data-toggle="tab" href="#nav-dashboard" role="tab" aria-controls="nav-dashboard" aria-selected="true">Dashboard</a>
          </li>
          {% for i in board %}
            <li class="nav-item">
              <a class="nav-link" id="nav-{{i|cut:" "}}-tab" data-toggle="tab" href="#nav-{{i.name|cut:" "}}" role="tab" aria-controls="nav-{{i|cut:" "}}" aria-selected="false">{{i}}</a>
            </li>
          {% endfor %}
          <li class="nav-item">
            <a class="nav-link">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              </svg>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid flex-container tab-content" style="padding:0px;">
      <div class="tab-pane container-fluid fade show active" id="nav-dashboard" role="tabpanel" aria-labelledby="nav-dashboard-tab">
        DASHBOARD
      </div>
      {% for i in board %}
        <div class="tab-pane container-fluid fade" id="nav-{{i|cut:" "}}" role="tabpanel" aria-labelledby="nav-{{i|cut:" "}}-tab">
          <div class="board-area-top">
            TOPBAR
          </div>
          <div class="board-area-body">
            {% for j in todo_list %}
              {% if j.board == i %}
                <div class="column">
                  <div class="card">
                    <div class="card-header">
                      <table style="width: 100%">
                        <tbody>
                          <tr>
                            <td>
                              <span>{{j}}</span>
                            </td>
                            <td>
                              <span class="dropdown">
                                <button class="btn list-options side-option float-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                                  </svg>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                  <a class="dropdown-item" href="#">Edit To-Do List</a>
                                  <a class="dropdown-item" href="#">Create New To-Do Item</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#">Delete</a>
                                </div>
                              </span>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <div class="sortable">
                      {% for k in j.todoitem_set.all %}
                        <div class="list-item ui-state-default">
                          <table style="width: 100%">
                            <tbody>
                              <tr>
                                <td>
                                  <div class="form-check-inline">
                                    <input type="checkbox" class="form-check-input" id="{{k|cut:" "}}-check">
                                    <label class="form-check-label" for="{{k|cut:" "}}-check">{{k}}</label>
                                  </div>
                                </td>
                                <td>
                                  <button class="btn side-option float-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                      <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                                    </svg>
                                  </button>
                                </td>
                              </tr>
                              {% for l in k.todosubitem_set.all %}
                            <tr>
                              <td>
                                <div class="form-check-inline subitem-list">
                                  <input type="checkbox" class="form-check-input" id="{{l|cut:" "}}-check">
                                  <label class="form-check-label" for="{{l|cut:" "}}-check">{{l}}</label>
                                </div>
                              </td>
                              <td>
                                <button class="btn side-option float-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                                  </svg>
                                </button>
                              </td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                        </div>
                      {% endfor %}
                      <!-- <div class="list-item">
                        <input type="text" id="new_list_item">
                      </div> -->
                    </div>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </body>
</html>